### ISSUE TITLE
登陆、注册问题

### ISSUE THREAD

**Issue by qzhqzh** [qzhqzh/cripserdx#8]
Request Method: | POST
-- | --
http://127.0.0.1:8000/myuser/resgister
3.1.2
ImproperlyConfigured
The module in NAME could not be imported: django.contrib.user.password_validation.UserAttributeSimilarityValidator. Check your AUTH_PASSWORD_VALIDATORS setting.
D:\virtualevn\cripserdx\lib\site-packages\django\contrib\auth\password_validation.py, line 29, in get_password_validators
D:\virtualevn\cripserdx\Scripts\python.exe
3.6.6
['D:\\github\\cripserdx',  'D:\\virtualevn\\cripserdx\\Scripts\\python36.zip',  'C:\\Users\\qzhu\\Anaconda3\\DLLs',  'C:\\Users\\qzhu\\Anaconda3\\lib',  'C:\\Users\\qzhu\\Anaconda3',  'D:\\virtualevn\\cripserdx',  'D:\\virtualevn\\cripserdx\\lib\\site-packages']
Wed, 28 Oct 2020 02:21:27 +0000

**Comment by hotwalter** [comment]
创建auth app后，发现和django 自带auth 冲突，修改app 名称，Pycharm 会自动修改django 中所有的Auth ,导致setting.py 中的 AUTH_PASSWORD_VALIDATORS 变量中的auth被替换成新该的app 名称，直接将app名称更换为以前的auth 即可。
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
